version: '3.8'

services:
  ef-runner:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: ef-runner
    depends_on:
      - sqlserver
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - dentalnet
    entrypoint: tail -f /dev/null  # Keeps the container running for manual commands

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "NewPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - dentalnet

  dentalapp-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dentalapp-api
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DentalAppSystem;User=sa;Password=NewPassword123!;TrustServerCertificate=True;Encrypt=False;
    networks:
      - dentalnet

networks:
  dentalnet:
